services:
  postgres:
    image: postgres:17

    container_name: atlas-postgres

    restart: unless-stopped

    ports:
      - '5433:5432'

    environment:
      POSTGRES_USER: atlas
      POSTGRES_PASSWORD: atlas
      POSTGRES_DB: atlas

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
