import { db } from "@/lib/db";
import { Prisma, ProcessingJob, ProcessingJobStatus } from "@prisma/client";
import { InvalidJobStateTransitionError, JobNotFoundError } from "../errors/processing-errors";

export class ProcessingService {
  /**
   * Creates a new processing job for a document.
   * Participates in a transaction if `tx` is provided.
   */
  async createJob(documentId: string, tx?: Prisma.TransactionClient): Promise<ProcessingJob> {
    const client = tx ?? db;

    return client.processingJob.create({
      data: {
        documentId,
        status: ProcessingJobStatus.PENDING,
      },
    });
  }

  /**
   * Atomically claims the next pending job.
   * Returns the job if successfully claimed, or null if no pending jobs exist.
   */
  async claimNextPendingJob(): Promise<ProcessingJob | null> {
    // We use a transaction to find and update a single row to prevent race conditions.
    // In PostgreSQL, FOR UPDATE SKIP LOCKED is the best way to do this,
    // but Prisma's findFirst doesn't support SKIP LOCKED out of the box natively
    // in a single query without raw SQL.
    // We'll use a raw query for atomic claiming to be safe against concurrency.

    // Note on ::"ProcessingJobStatus": This is a PostgreSQL type cast to the custom enum generated by Prisma.
    // If the enum name in schema.prisma changes, this string must be updated to match the new type name.
    const result = await db.$queryRaw<ProcessingJob[]>`
      UPDATE "ProcessingJob"
      SET
        status = ${ProcessingJobStatus.PROCESSING}::"ProcessingJobStatus",
        "startedAt" = NOW(),
        "updatedAt" = NOW()
      WHERE id = (
        SELECT id
        FROM "ProcessingJob"
        WHERE status = ${ProcessingJobStatus.PENDING}::"ProcessingJobStatus"
        ORDER BY "createdAt" ASC
        LIMIT 1
        FOR UPDATE SKIP LOCKED
      )
      RETURNING *;
    `;

    if (!result || result.length === 0) {
      return null;
    }

    return result[0];
  }

  /**
   * Completes a processing job.
   * Ensures the job is currently in the PROCESSING state.
   */
  async completeJob(jobId: string): Promise<ProcessingJob> {
    return db.$transaction(async (tx) => {
      const job = await tx.processingJob.findUnique({ where: { id: jobId } });
      if (!job) {
        throw new JobNotFoundError(jobId);
      }

      if (job.status !== ProcessingJobStatus.PROCESSING) {
        throw new InvalidJobStateTransitionError(jobId, job.status, ProcessingJobStatus.COMPLETED);
      }

      return tx.processingJob.update({
        where: { id: jobId },
        data: {
          status: ProcessingJobStatus.COMPLETED,
          completedAt: new Date(),
        },
      });
    });
  }

  /**
   * Fails a processing job, records the error, and increments the attempt count.
   * Ensures the job is currently in the PROCESSING state.
   */
  async failJob(jobId: string, error: string, isRetriable: boolean = true): Promise<ProcessingJob> {
    return db.$transaction(async (tx) => {
      const job = await tx.processingJob.findUnique({ where: { id: jobId } });
      if (!job) {
        throw new JobNotFoundError(jobId);
      }

      if (job.status !== ProcessingJobStatus.PROCESSING) {
        throw new InvalidJobStateTransitionError(jobId, job.status, ProcessingJobStatus.FAILED);
      }

      const updateData: Prisma.ProcessingJobUpdateInput = {
        status: ProcessingJobStatus.FAILED,
        lastError: error,
      };

      if (isRetriable) {
        updateData.attemptCount = { increment: 1 };
      }

      return tx.processingJob.update({
        where: { id: jobId },
        data: updateData,
      });
    });
  }
}

export const processingService = new ProcessingService();
